FROM alpine/git:latest


RUN apk add --no-cache     build-base     gcc     g++     make     flex     bison     elfutils-dev     openssl-dev     perl     bash     ncurses-dev     python3     bc     git     kmod


WORKDIR /kernel
